@api = https://resapi.vercel.app/tasks

###
GET https://resapi.vercel.app/tasks

###
POST https://resapi.vercel.app/tasks
Content-Type: application/json

{
  "name": "create a website",
  "description": "using Nodejs and express"
}

### update
PUT https://resapi.vercel.app/tasks/34d775aa-b0de-4f7c-a9c1-58af1a29e9fe
Content-Type: application/json

{
  "name": "hello",
  "description": "world"
}

### get total tasks
{{api}}/count